# Generated by Django 5.1.4 on 2025-05-16 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0002_customeraddress_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerAddress',
        ),
    ]
