# Generated by Django 5.1.4 on 2025-05-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0005_profile_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='alternate_mobile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
